### ISSUE TITLE
Comparison with similar packages

### ISSUE THREAD

**Issue by dandv** [dpid/meteor-user-presence#2]
Hello,

How does this package compare with [similar packages](https://github.com/VeliovGroup/Meteor-user-status/issues/1), such as @mizzao's user-status, or @dburles's [presence](https://github.com/dburles/meteor-presence/issues/1) package?

**Comment by dpid** [comment]
@mizzao's user-status package is way more robust and should be used if you need those features.
@dburles's presence package is extremely similar. The difference in meteor-user-presence package is how it handles disconnects and gives you an optional callback function option for that event.

The main intention of this package was to accompany the meteor chat room demo I made which needed this extra functionality.

https://github.com/dpid/meteor-chat-room
